name: validate renovate

on:
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/workflows/validate-renovate.yml'
  push:
    paths:
      - 'renovate.json'
      - '.github/workflows/validate-renovate.yml'

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@ee9f69e1f683ed0d08225086482b34fc9abe9300 # v2.1.0
